Footer component
Selleo/mikstura.it pull request #3
Opened 2020-06-22 14:49 UTC by JakubBrozek

# Tasks 
- Adding footer on page
- Adding icons
- Adding links to socialmedia
- Styling `Footer` and it's elements

# Steps 
- [ ] Added `Footer` component
- [ ] Styled `footer-wrapper` and icons
- [ ] Activated links to socialmedia
- [ ] Added footer line with gradient
- [ ] Added client's logo in the background
- [ ] Added `credits` with year 

# Preview
![image](https://user-images.githubusercontent.com/30187523/85301454-249d1080-b4a8-11ea-92fd-8e9d7df49d2f.png)

2020-06-22 15:12 UTC, wozny1989 commented on src/components/footer.js
> +      <a href="https://www.meetup.com/Mikstura-IT/" className='footer-link' activeClassName='active'><i class="fab fa-meetup"></i></a>
I guess `activeClassNames` it not necessary in this cases (in all social links) ✂️

2020-06-22 15:34 UTC, wozny1989 commented on src/fontawesome/LICENSE.txt
> +to represent the company, product, or service to which they refer.**
Remove this file ✂️

2020-06-22 15:41 UTC, wozny1989 commented on src/styles/stylesheet.css
> +}
Consider set static `width` and `height` to make sure we have square, not an oval. Also set after this `aling-items: center` to align icons in squares.

2020-06-22 15:43 UTC, wozny1989 commented on src/styles/stylesheet.css
> +  margin: 0 auto;
Think about to replace `0` to some value to make a little vertical margin.

2020-06-22 15:43 UTC, wozny1989 commented on src/styles/stylesheet.css
> +.footer-link.active{
`.active` ✂️

2020-06-22 15:46 UTC, wozny1989 requested changes
Great pull request documentation, keep it up! 🎉 🎉 🎉

2020-06-24 09:04 UTC, wozny1989 commented on src/styles/stylesheet.css
> +  justify-content: space-evenly;
Maybe better use `center`

2020-06-24 09:09 UTC, wozny1989 commented on src/styles/stylesheet.css
> +  border-color: #404040;
You use several times the same color `#404040`. Consider set it in variable.

2020-06-24 09:26 UTC, wozny1989 commented on src/components/layout.js
> +        <Footer />
Maybe better way will be move that `<Footer />` below `content` container and set width. Just for make some empty place you can set in `content` some static height and then you can get rid of `align-items: flex-end` in `content` class. (`flex-end` will be undesirable behavior when you pass some data to `Layout` component)

2020-06-24 09:27 UTC, wozny1989 commented on src/components/footer.js
> +    <div className='footer-credits'>© {new Date().getFullYear()} Selleo</div>
Looks great! 🎉

2020-06-24 09:28 UTC, wozny1989 requested changes
@JakubBrozek Some small feedback 👏

2020-06-24 09:29 UTC, wozny1989 commented on src/styles/stylesheet.css
> +  --secondary-color: #404040;
❤️

2020-06-24 09:32 UTC, JakubBrozek commented on src/styles/stylesheet.css
> +  --secondary-color: #404040;
We're on fire 👯

2020-06-25 11:19 UTC, wozny1989 commented on src/components/layout.js
>        <div className='content'>
Use bootstrap class `container` (to make a responsive)

2020-06-25 11:23 UTC, wozny1989 requested changes

2020-06-25 11:23 UTC, wozny1989 commented on src/styles/stylesheet.css
>  }
Change class name to `.container` and remove static `width` field. Look at the behavior page in different size.

2020-06-25 11:23 UTC, wozny1989 commented on src/components/layout.js
>        <div className='content'>
Use bootstrap class `container` (to make a responsive)

2020-06-25 11:38 UTC, merged